obj-$(CONFIG_GORILLA_MEMC)      += gorilla-memc.o
obj-$(CONFIG_GORILLA_EXTRA_MEM) += gorilla-extra-mem.o
obj-$(CONFIG_GORILLA_NSI)       += gorilla-nsi.o
obj-$(CONFIG_GORILLA_DE_TCON)   += gorilla-de-tcon.o