# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_SUNXI_SRAM) +=	sunxi_sram.o
obj-$(CONFIG_GPU_PM_DOMAINS) += gpu_domain.o
obj-$(CONFIG_SUNXI_SID) +=        sunxi-sid.o
obj-$(CONFIG_SUNXI_DUMP) +=       sunxi-dump.o
obj-$(CONFIG_SUNXI_RISCV_SUSPEND) += sunxi_riscv_pm.o
obj-$(CONFIG_PM_TRACE_NVMEM) += pm_trace_nvmem.o
obj-m += vf-test.o
