#
# Makefile for the sensor:wq drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_SC7A20)    += sc7a20.o
obj-$(CONFIG_STK3X1X) 		+= stk3x1x.o
obj-$(CONFIG_SENSORS_MIR3DA)    += mir3da/
obj-$(CONFIG_SUNXI_TPADC)       += sunxi_tpadc.o
obj-$(CONFIG_SUNXI_GPADC) 	+= sunxi_gpadc.o
